// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0ExJPls17RP_SsS0j_BNB0VFDQuQux0',
    appId: '1:599125428038:android:0cdbd077d7cdface504747',
    messagingSenderId: '599125428038',
    projectId: 'backend-pratice',
    databaseURL: 'https://backend-pratice-default-rtdb.firebaseio.com',
    storageBucket: 'backend-pratice.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUctpX7roDa5BWQPKZOFwjRT9ndkGgpLs',
    appId: '1:599125428038:web:7601909b182b79da504747',
    messagingSenderId: '599125428038',
    projectId: 'backend-pratice',
    authDomain: 'backend-pratice.firebaseapp.com',
    databaseURL: 'https://backend-pratice-default-rtdb.firebaseio.com',
    storageBucket: 'backend-pratice.firebasestorage.app',
    measurementId: 'G-TK59J0JWNK',
  );
}
